name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-24.04
          - os: macos-15
          - os: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: pnpm install

      - name: Code quality
        run: pnpm quality:ci

      - name: Test
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - name: Test
        run: npm test
        if: runner.os != 'Linux'

      - name: Build
        run: pnpm compile
